import type { Metadata } from "next";
import "./globals.css";

import { CursorTrail, TwinklingStars } from "@z/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        {/* Link to Google Fonts */}
        <link
          href='https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap'
          rel='stylesheet'
        />
      </head>
      <body className='antialiased' style={{ fontFamily: "'Inter', sans-serif" }}>
        <TwinklingStars />
        {children}
        <CursorTrail />
      </body>
    </html>
  );
}
