import type { Metadata } from "next";
import { Inter } from "@next/font/google";
import "./globals.css";

import { CursorTrail } from "@z/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"], // Optional subsets
  variable: "--font-inter", // Optional custom CSS variable
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} antialiased`}>
        {children}
        <CursorTrail />
      </body>
    </html>
  );
}
